### ISSUE TITLE
t2.small ec2 memory

### ISSUE THREAD

**Issue by bigdriveca** [SocialHarvest/harvester#67]
Hi:

I'm running on a t2.small at Amazon EC2 and when I fire up ./harvester I get:

fatal error: runtime: out of memory

I know, I'm cheap and I can go up a few notches - just wondering if there are any Go optimizations that I might be missing.

D.

**Comment by tmaiaroto** [comment]
You'd need to disable things in the source code such as the sentiment analysis and geocoding (geobed package). Both of these put a fair amount of data into RAM for two reasons: 1. To not require a database so deployments are easier and everything is self contained (well, aside from pulling down the data set - though you could manually put that in a server image for example) and 2. To be fast. 

As a result, you're going to need at least 512MB of RAM on the server. I have ran this on a Digital Ocean server with 512MB of RAM I believe. I can double check, but if not that then a 1GB Digital Ocean server for sure. Which are both still quite inexpensive. Reading through Amazon's info, the t2.small claims to have 2GB of RAM but I'm curious if that's "burstable" which might explain why you're getting the out of memory.

It's not configurable, but you could even use the geocoder with a smaller data set... Just fork and comment out: https://github.com/SocialHarvest/geobed/blob/master/geobed.go#L37

Then you'd fork the harvester (this repo) and alter the following import:
https://github.com/SocialHarvest/harvester/blob/7516ae03c41c44c2c40ceec82a2d206ef2f0d3e9/lib/harvester/harvester.go#L23

To instead point to your fork. Two minor edits and that should allow you to build a version of the harvester that works with a lot less geolocation data. So your accuracy in reversing location text that people put in their Twitter profiles will be lowered, but you'll still get some.

I'm still trying to figure out how to optimize all this and I've been going back and forth on the idea of using some API...But that incurs more cost (and geocoding is SUPER expensive when you need to make millions of requests). So I made the geobed package to keep a city level accuracy on things, for free, at a speedy rate. Remember the API approach is going to be slower due to all the additional HTTP requests.

As always, I'm open to ideas and thoughts. Thanks.

**Comment by bigdriveca** [comment]
Hi Tom - thanks for the details. I'll do some poking around. BTW I share your philosophy on getting data to the average bear. These proprietary data mountains need to be opened up.

**Comment by tmaiaroto** [comment]
I'm changing the entire system around to work in a more (micro) service oriented way (SoA). This means the geocoder will be a microservice and you'll be able to swap that piece out in the chain to use one that is less memory intensive. Or perhaps one that uses some API somewhere (really memory efficient, just perhaps slower).

The microservices will indeed communicate on different ports, but that doesn't mean you'll need to have multiple servers or even multiple binaries. It will be designed in such a manner that you will be able to build one binary and run one binary. The difference is, you'll be able to swap out services or components so you can get around this limitation.

Side note: This is the ground work for a more modular system where you will be able to pipe data in from all over the place and modifying data flowing through the system.

I am definitely looking into this still. I didn't want you to think I forgot =)

**Comment by tmaiaroto** [comment]
Update on this: The "microservices" will come in version 2.0. I don't want to make such a drastic change at this time. Regardless, I will try to put all of this data for machine learning and location lookups into something like boltdb which uses memory mapped files. This way, it should work with a server of almost any size, but be far slower on smaller servers...But at least work. In theory.

The challenge here is that writing all of that data to a memory mapped file has been a challenge. Once I can get it written though, distributing it via S3 will be as easy as it is now.

I'm going to close this issue and open a new one labeled as an enhancement. I do want Social Harvest to run on cheap hardware do this is important to me. However, we are talking about a _lot_ of data. As much as I like to make "big" data "small" - a few gigabytes of RAM is getting to be more affordable these days. Try DigitalOcean for hosting. You can even get started with $10 in credit by using my referrer code: https://www.digitalocean.com/?refcode=013e282b3ac6 (and it helps support me in the development of SocialHarvest because I use DigitalOcean for test/development).

**Comment by tmaiaroto** [comment]
See: #72
